nsc-events-2-26-create-templates-for-main
SeattleColleges/nsc-events pull request #27
Opened 2024-01-29 23:36 UTC by taylorpapke

Resolves #26

This PR adds the templates to the main repo for user story, issue and pull request.

2024-01-30 22:48 UTC, brinkbrink requested changes
Awesome, thanks Taylor! I don't see anything jumping out at me to change or fix except maybe including a prompt to include screenshots/gifs/videos/diagrams/other visual aids where applicable. I know that's something that has been helpful in the past.

2024-02-29 23:16 UTC, heosman submitted a review, later dismissed

2024-04-12 07:56 UTC, taylorpapke commented
I modified this existing PR to instead achieve the goal of deleting all templates. They've all been added to the .github repo where they can be centrally managed for all repos.

2024-04-13 23:51 UTC, bcko commented
> I modified this existing PR to instead achieve the goal of deleting all templates. They've all been added to the .github repo where they can be centrally managed for all repos.

Thanks!

2024-04-13 23:51 UTC, bcko approved these changes

2024-04-13 23:52 UTC, merged